<?php

namespace ContainerE7ES9h7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XihMA0MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XihMA0M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XihMA0M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ConsultaController::delete' => ['privates', '.service_locator.gkK44G7', 'get_ServiceLocator_GkK44G7Service', true],
            'App\\Controller\\ConsultaController::edit' => ['privates', '.service_locator.gkK44G7', 'get_ServiceLocator_GkK44G7Service', true],
            'App\\Controller\\ConsultaController::index' => ['privates', '.service_locator.rey0eH_', 'get_ServiceLocator_Rey0eHService', true],
            'App\\Controller\\ConsultaController::show' => ['privates', '.service_locator.gkK44G7', 'get_ServiceLocator_GkK44G7Service', true],
            'App\\Controller\\PacienteController::delete' => ['privates', '.service_locator.qLZw2eN', 'get_ServiceLocator_QLZw2eNService', true],
            'App\\Controller\\PacienteController::edit' => ['privates', '.service_locator.qLZw2eN', 'get_ServiceLocator_QLZw2eNService', true],
            'App\\Controller\\PacienteController::index' => ['privates', '.service_locator.CoOJND7', 'get_ServiceLocator_CoOJND7Service', true],
            'App\\Controller\\PacienteController::show' => ['privates', '.service_locator.qLZw2eN', 'get_ServiceLocator_QLZw2eNService', true],
            'App\\Controller\\RecetaController::delete' => ['privates', '.service_locator.IDWPcKX', 'get_ServiceLocator_IDWPcKXService', true],
            'App\\Controller\\RecetaController::edit' => ['privates', '.service_locator.IDWPcKX', 'get_ServiceLocator_IDWPcKXService', true],
            'App\\Controller\\RecetaController::index' => ['privates', '.service_locator.hNhEJGw', 'get_ServiceLocator_HNhEJGwService', true],
            'App\\Controller\\RecetaController::show' => ['privates', '.service_locator.IDWPcKX', 'get_ServiceLocator_IDWPcKXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ConsultaController:delete' => ['privates', '.service_locator.gkK44G7', 'get_ServiceLocator_GkK44G7Service', true],
            'App\\Controller\\ConsultaController:edit' => ['privates', '.service_locator.gkK44G7', 'get_ServiceLocator_GkK44G7Service', true],
            'App\\Controller\\ConsultaController:index' => ['privates', '.service_locator.rey0eH_', 'get_ServiceLocator_Rey0eHService', true],
            'App\\Controller\\ConsultaController:show' => ['privates', '.service_locator.gkK44G7', 'get_ServiceLocator_GkK44G7Service', true],
            'App\\Controller\\PacienteController:delete' => ['privates', '.service_locator.qLZw2eN', 'get_ServiceLocator_QLZw2eNService', true],
            'App\\Controller\\PacienteController:edit' => ['privates', '.service_locator.qLZw2eN', 'get_ServiceLocator_QLZw2eNService', true],
            'App\\Controller\\PacienteController:index' => ['privates', '.service_locator.CoOJND7', 'get_ServiceLocator_CoOJND7Service', true],
            'App\\Controller\\PacienteController:show' => ['privates', '.service_locator.qLZw2eN', 'get_ServiceLocator_QLZw2eNService', true],
            'App\\Controller\\RecetaController:delete' => ['privates', '.service_locator.IDWPcKX', 'get_ServiceLocator_IDWPcKXService', true],
            'App\\Controller\\RecetaController:edit' => ['privates', '.service_locator.IDWPcKX', 'get_ServiceLocator_IDWPcKXService', true],
            'App\\Controller\\RecetaController:index' => ['privates', '.service_locator.hNhEJGw', 'get_ServiceLocator_HNhEJGwService', true],
            'App\\Controller\\RecetaController:show' => ['privates', '.service_locator.IDWPcKX', 'get_ServiceLocator_IDWPcKXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ConsultaController::delete' => '?',
            'App\\Controller\\ConsultaController::edit' => '?',
            'App\\Controller\\ConsultaController::index' => '?',
            'App\\Controller\\ConsultaController::show' => '?',
            'App\\Controller\\PacienteController::delete' => '?',
            'App\\Controller\\PacienteController::edit' => '?',
            'App\\Controller\\PacienteController::index' => '?',
            'App\\Controller\\PacienteController::show' => '?',
            'App\\Controller\\RecetaController::delete' => '?',
            'App\\Controller\\RecetaController::edit' => '?',
            'App\\Controller\\RecetaController::index' => '?',
            'App\\Controller\\RecetaController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ConsultaController:delete' => '?',
            'App\\Controller\\ConsultaController:edit' => '?',
            'App\\Controller\\ConsultaController:index' => '?',
            'App\\Controller\\ConsultaController:show' => '?',
            'App\\Controller\\PacienteController:delete' => '?',
            'App\\Controller\\PacienteController:edit' => '?',
            'App\\Controller\\PacienteController:index' => '?',
            'App\\Controller\\PacienteController:show' => '?',
            'App\\Controller\\RecetaController:delete' => '?',
            'App\\Controller\\RecetaController:edit' => '?',
            'App\\Controller\\RecetaController:index' => '?',
            'App\\Controller\\RecetaController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
