<?php

namespace ContainerE7ES9h7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HNhEJGwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hNhEJGw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hNhEJGw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recetaRepository' => ['privates', 'App\\Repository\\RecetaRepository', 'getRecetaRepositoryService', true],
        ], [
            'recetaRepository' => 'App\\Repository\\RecetaRepository',
        ]);
    }
}
