<?php

namespace ContainerE7ES9h7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPacienteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qLZw2eN.App\Entity\Paciente' shared service.
     *
     * @return \App\Entity\Paciente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qLZw2eN": it references class "App\\Entity\\Paciente" but no such service exists.');
    }
}
