<?php

namespace ContainerCTB5oKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IDWPcKXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IDWPcKX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IDWPcKX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recetum' => ['privates', '.errored..service_locator.IDWPcKX.App\\Entity\\Receta', NULL, 'Cannot autowire service ".service_locator.IDWPcKX": it references class "App\\Entity\\Receta" but no such service exists.'],
        ], [
            'recetum' => 'App\\Entity\\Receta',
        ]);
    }
}
