<?php

namespace ContainerCTB5oKW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GkK44G7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gkK44G7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gkK44G7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consultum' => ['privates', '.errored..service_locator.gkK44G7.App\\Entity\\Consulta', NULL, 'Cannot autowire service ".service_locator.gkK44G7": it references class "App\\Entity\\Consulta" but no such service exists.'],
        ], [
            'consultum' => 'App\\Entity\\Consulta',
        ]);
    }
}
